//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE104_QLNS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOCONGNO
    {
        public byte Thang { get; set; }
        public byte Nam { get; set; }
        public string MaKH { get; set; }
        public Nullable<decimal> NoDau { get; set; }
        public Nullable<decimal> PhatSinh { get; set; }
        public Nullable<decimal> NoCuoi { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
