//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE104_QLNS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOTON
    {
        public byte Thang { get; set; }
        public byte Nam { get; set; }
        public string MaSach { get; set; }
        public Nullable<int> TonDau { get; set; }
        public Nullable<int> PhatSinh { get; set; }
        public Nullable<int> TonCuoi { get; set; }
    
        public virtual SACH SACH { get; set; }
    }
}
